import { afterEach, expect, it, vi } from "vitest";
import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { exec } from "../../server/worktree-exec.ts";
import { getWorktreeDiff } from "../../server/commands/get-worktree-diff.ts";
import { isReviewDiff } from "../../shared/review-diff.ts";
import { setup, cmd } from "../support/server-command-harness.ts";
let root: string | undefined;
afterEach(async () => { if (root) await fs.rm(root, { recursive: true, force: true }); });
it("the real command delivers bounded inspectable evidence only on the requesting run topic", async () => {
  root = await fs.mkdtemp(path.join(os.tmpdir(), "review-contract-"));
  await exec(["init", "-b", "main"], root);
  await fs.writeFile(path.join(root, "text.txt"), "new\n");
  await fs.writeFile(path.join(root, "image.bin"), Buffer.from([0, 1]));
  const h = setup({ sessionKey: "review-run", cwd: root });
  getWorktreeDiff(h.ctx, cmd({ type: "get_worktree_diff", sessionKey: "review-run", requestId: "read-only" }), h.ws);
  await vi.waitFor(() => expect(h.wsSent).toHaveLength(1));
  const message = h.wsSent[0]!;
  expect(message).toMatchObject({ type: "control_response", topic: "session:review-run", sessionKey: "review-run", requestId: "read-only", success: true });
  const diff = message["diff"];
  expect(isReviewDiff(diff)).toBe(true);
  if (!isReviewDiff(diff)) throw new Error("Invalid review contract");
  expect(diff.snapshot).toMatchObject({ runKey: "review-run", baseSha: null, contributionBinding: "unbound", consistency: "sampled" });
  expect(diff.files.find(f => f.file === "text.txt")?.patch?.text).toContain("+new");
  expect(diff.files.find(f => f.file === "image.bin")?.patch?.state).toBe("binary");
  expect(h.busSent).toHaveLength(0);
  expect((await exec(["ls-files"], root)).stdout).toBe("");
});
