import { openProjectFixture } from "./project-fixture.mjs";
import { expect, test } from "@playwright/test";

test("switches, fits, saves, and reloads workspace canvases with a permanent Global", async ({ page }) => {
  const errors = [];
  page.on("pageerror", error => errors.push(error.message));
  await page.setViewportSize({ width: 1440, height: 1000 });
  await openProjectFixture(page, "Workspace Journey");
  await page.getByRole("tab", { name: "Canvas" }).click();
  const openWorkspaces = async () => {
    const toggle = page.getByRole("button", { name: /^Workspaces ·/ });
    if (await toggle.getAttribute("aria-expanded") === "false") await toggle.click();
  };
  await expect(page.getByRole("region", { name: "Choose workspace" })).toHaveCount(0);
  await openWorkspaces();
  const global = page.getByRole("button", { name: "Switch to Global", exact: true });
  const cards = page.locator('[data-canvas-node-id]:visible');
  await expect(global).toHaveAttribute("aria-current", "true");
  await expect(page.getByText("Workspace settings", { exact: true })).toHaveCount(0);
  const paste = async (text) => {
    await page.evaluate(content => {
      const data = new DataTransfer(); data.setData("text/plain", content);
      document.body.dispatchEvent(new ClipboardEvent("paste", { clipboardData: data, bubbles: true, cancelable: true }));
    }, text);
    await expect(cards).toHaveCount(1);
  };
  await paste("Global research notes");
  await openWorkspaces();
  await page.getByRole("button", { name: "New workspace", exact: true }).click();
  await page.getByRole("textbox", { name: "Workspace name" }).fill("Release");
  await page.getByRole("button", { name: "Save workspace" }).click();
  const release = page.getByRole("button", { name: "Switch to Release", exact: true });
  await openWorkspaces();
  await expect(release).toHaveAttribute("aria-current", "true");
  await expect(cards).toHaveCount(0);
  const saved = page.waitForResponse(response => response.request().method() === "PUT" && response.url().endsWith("/state") && response.ok());
  await paste("Release planning notes");
  await saved;
  await openWorkspaces();
  await global.click();
  await expect(cards).toHaveCount(1);
  await expect(cards.first()).toContainText("Global research notes");
  const switchedSave = page.waitForResponse(response => response.request().method() === "PUT" && response.url().endsWith("/state") && response.ok());
  await openWorkspaces();
  await release.click();
  await expect(cards.first()).toContainText("Release planning notes");
  const box = await cards.first().boundingBox();
  expect(box.x).toBeGreaterThanOrEqual(0);
  expect(box.y).toBeGreaterThanOrEqual(0);
  expect(box.x + box.width).toBeLessThanOrEqual(1440 - 24);
  expect(box.y + box.height).toBeLessThanOrEqual(1000);
  await expect(page.getByRole("button", { name: /Return.*canvas/ })).toHaveCount(0);
  // Save the selected workspace before reload.
  await switchedSave;
  await page.reload();
  await page.getByText("Workspace Journey", { exact: true }).click();
  await page.getByRole("tab", { name: "Canvas" }).click();
  await openWorkspaces();
  await expect(release).toHaveAttribute("aria-current", "true");
  await expect(cards).toHaveCount(1);
  await expect(cards.first()).toContainText("Release planning notes");
  await page.screenshot({ path: "/tmp/canvas-workspaces-desktop.png" });
  await page.getByRole("button", { name: "Settings for Release" }).click();
  await expect(page.getByRole("button", { name: "Rename workspace" })).toBeVisible();
  await page.keyboard.press("Escape");
  await expect(page.getByRole("button", { name: "Rename workspace" })).toHaveCount(0);
  await page.keyboard.press("Escape");
  await expect(page.getByRole("region", { name: "Choose workspace" })).toHaveCount(0);
  await expect(page.getByRole("button", { name: "Workspaces · Release" })).toBeFocused();
  await page.screenshot({ path: "/tmp/canvas-workspaces-collapsed.png" });
  await page.setViewportSize({ width: 720, height: 900 });
  const toggle = page.getByRole("button", { name: "Workspaces · Release" });
  await expect(toggle).toBeVisible();
  await toggle.click();
  await openWorkspaces();
  await global.click();
  await expect(cards.first()).toContainText("Global research notes");
  await page.screenshot({ path: "/tmp/canvas-workspaces-narrow.png" });
  expect(errors).toEqual([]);
});
