import { test, expect } from '@playwright/test';
import { openResponsiveFixture } from './responsive-fixture.mjs';

const html = `<!doctype html><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; img-src data:"><style>body{font:18px system-ui;padding:28px}section{background:#eee;padding:24px}p{padding:14px;color:#333}</style><section><h2>Newsletter</h2><p id="signup">Subscribe</p></section>`;

test('dashboard HTML review captures, previews, exports, and remains inert on desktop and phone', async ({ page }, info) => {
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.setViewportSize({ width: 1440, height: 1000 });
  const fixture = await openResponsiveFixture(page);
  await page.getByRole('button', { name: "Review request: Improve responsive layouts across laptop screens" }).click();
  fixture.send({ type: 'render_update', sessionKey: 'layout-0', leaderSessionKey: 'layout-0', action: 'set', components: [{ id: 'review', type: 'html-artifact', title: 'Newsletter review', html }] });
  await page.getByRole('tab', { name: 'Dashboard', exact: true }).click();
  await page.getByRole('button', { name: 'Review & annotate' }).click();
  const review = page.getByRole('region', { name: 'HTML feedback workspace' });
  const frame = page.frameLocator('iframe[title="HTML review viewport"]');
  await frame.getByText('Subscribe', { exact: true }).click();
  const selection = review.locator('.hf-outline');
  const selectedBounds = await selection.getAttribute('style');
  await expect(selection).toHaveCSS('outline-color', 'rgb(37, 99, 235)');
  await frame.getByRole('heading', { name: 'Newsletter' }).hover();
  await expect(review.locator('.hf-hover-outline')).toHaveCSS('outline-color', 'rgb(220, 38, 38)');
  await expect(selection).toHaveAttribute('style', selectedBounds);
  await review.getByLabel('What should change?').hover();
  await review.getByLabel('What should change?').fill('Match the heading alignment. Keep the current color.');
  await expect(selection).toBeVisible();
  await expect(selection).toHaveAttribute('style', selectedBounds);
  await expect(review.locator('.hf-hover-outline')).toHaveCount(0);
  // Moving to another target keeps the previous note automatically.
  await frame.getByRole('heading', { name: 'Newsletter' }).click();
  await expect(selection).not.toHaveAttribute('style', selectedBounds);
  await expect(review.getByLabel('What should change?')).toHaveValue('');
  await frame.getByText('Subscribe', { exact: true }).click();
  await expect(selection).toHaveAttribute('style', selectedBounds);
  await review.getByRole('button', { name: 'Edit selected text', exact: true }).click();
  await frame.getByRole('textbox', { name: 'Edit selected text' }).fill('Join the newsletter');
  await expect(frame.getByText('Join the newsletter', { exact: true })).toBeVisible();
  await review.getByRole('button', { name: 'Cancel text edit' }).click();
  await expect(frame.getByText('Subscribe', { exact: true })).toBeVisible();
  await review.getByRole('button', { name: 'New note' }).click();
  await expect(review.locator('strong').filter({ hasText: 'F01' })).toBeVisible();
  await expect(selection).toHaveCount(0);
  await review.getByRole('button', { name: 'Draw region' }).click();
  const viewportBounds = await page.locator('iframe[title="HTML review viewport"]').boundingBox();
  await page.mouse.move(viewportBounds.x + 80, viewportBounds.y + 300);
  await page.mouse.down();
  await page.mouse.move(viewportBounds.x + 300, viewportBounds.y + 380, { steps: 4 });
  await expect(review.locator(".hf-region-draft")).toBeVisible();
  await page.mouse.up();
  await expect(review.getByRole('button', { name: 'Select', exact: true })).toHaveAttribute('aria-pressed', 'true');
  await expect(review.getByRole('group', { name: 'Selection actions' })).toContainText('Selected region');
  await review.getByLabel('What should change?').fill('Reduce this empty space.');
  await review.getByRole('button', { name: 'New note' }).click();
  await review.getByRole('button', { name: 'Next note' }).click();
  await expect(review.locator('strong').filter({ hasText: 'F02' })).toBeVisible();
  await review.getByRole('button', { name: 'Select', exact: true }).click();
  await frame.getByText('Subscribe', { exact: true }).click();
  await expect(review.getByRole('heading', { name: 'Note F01' })).toBeVisible();
  await expect(review.locator('.hf-annotation[data-selected=true]')).toHaveCSS('border-color', 'rgb(37, 99, 235)');
  await expect(review.locator('.hf-canvas')).toHaveText('');
  await expect(review.getByRole('group', { name: 'Selection actions' })).not.toContainText('F01');
  await expect(review.locator('.hf-outline')).toBeVisible();
  await review.getByRole('button', { name: 'Select', exact: true }).click();
  await frame.getByRole('heading', { name: 'Newsletter' }).hover();
  await expect(review.locator('.hf-outline')).toBeVisible();
  await expect(review.locator('.hf-hover-outline')).toBeVisible();
  await review.getByLabel('What should change?').fill('Align with the heading. Keep the current color.');
  await expect(review.getByRole('button', { name: 'Review 2 notes' })).toBeEnabled();
  await expect(review.getByLabel('What should change?')).toHaveValue('Align with the heading. Keep the current color.');
  await expect(review.getByRole('button', { name: 'Review 2 notes' })).toBeEnabled();
  await review.getByText('Export & storage', { exact: true }).click();
  const download = page.waitForEvent('download');
  await review.getByRole('button', { name: 'Export JSON' }).click();
  const file = await download;
  expect(file.suggestedFilename()).toBe('feedback.json');
  const chunks = [];
  for await (const chunk of await file.createReadStream()) chunks.push(chunk);
  const exported = JSON.parse(Buffer.concat(chunks).toString());
  expect(exported.items).toHaveLength(2);
  expect(exported.items[0].request).toBe('Align with the heading. Keep the current color.');
  expect(exported.items[1].target.kind).toBe('region');
  expect(exported.captures[0].html).toBe(html);
  await review.getByText('Export & storage', { exact: true }).click();
  await review.evaluate(el => { el.scrollTop = 0; el.querySelector('.hf-sidebar-body').scrollTop = 0; });
  await expect(review.getByRole('textbox')).toHaveCount(1);
  for (const selector of ['.hf-sidebar', '.hf-sidebar-body', '.hf-batch-footer']) {
    expect(await review.locator(selector).evaluate(el => el.scrollHeight <= el.clientHeight + 1)).toBe(true);
  }
  await page.screenshot({ path: info.outputPath('html-feedback-desktop.png') });
  await review.getByRole('button', { name: 'Review 2 notes' }).click();
  await expect(review.getByRole('button', { name: 'Submit batch (2 notes)' })).toBeEnabled();
  await expect(review.getByRole('heading', { name: 'Ready to send?' })).toBeFocused();
  await page.screenshot({ path: info.outputPath('html-feedback-desktop-review.png') });
  await review.getByRole('button', { name: 'Continue annotating' }).click();
  await expect(review.getByRole('button', { name: 'Select', exact: true })).toBeFocused();
  await review.getByRole('button', { name: 'Next note' }).click();
  await review.getByRole('button', { name: 'Inspect note F02' }).click();
  await expect(review.getByLabel('What should change?')).toHaveValue('Reduce this empty space.');
  await review.getByRole('button', { name: 'Discard changes' }).click();
  await expect(review.locator('.hf-annotation')).toHaveCount(1);
  await expect(review.getByRole('button', { name: 'Review 1 note' })).toBeEnabled();
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(review).toBeVisible();
  await review.getByRole('combobox', { name: 'Viewport', exact: true }).selectOption('360');
  await review.evaluate(el => { el.scrollTop = 0; });
  expect((await review.boundingBox()).width).toBeLessThanOrEqual(390);
  await page.screenshot({ path: info.outputPath('html-feedback-phone.png') });
  await review.getByRole('button', { name: 'Inspect note F01' }).click();
  await expect(review.getByLabel('What should change?')).toHaveValue('Align with the heading. Keep the current color.');
  await review.getByLabel('What should change?').fill('Align with the heading. Keep the current color and wording.');
  await expect(review.getByRole('button', { name: 'Review 1 note' })).toBeEnabled();
  await review.locator('.hf-sidebar-body').evaluate(el => { el.scrollTop = 0; });
  await page.screenshot({ path: info.outputPath('html-feedback-phone-inspector.png') });
  await review.getByRole('button', { name: 'Show more preview' }).click();
  await expect(review.getByLabel('What should change?')).not.toBeVisible();
  await review.getByRole('button', { name: 'Continue note' }).click();
  await expect(review.getByLabel('What should change?')).toBeVisible();
  await review.getByRole('button', { name: 'Review 1 note' }).click();
  await expect(review.getByRole('button', { name: 'Submit batch (1 note)' })).toBeVisible();
  await page.screenshot({ path: info.outputPath('html-feedback-phone-review.png') });
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.getByRole('button', { name: 'Close Newsletter review feedback' }).click();
  await page.getByRole('button', { name: 'Review & annotate' }).click();
  await expect(review.locator('strong').filter({ hasText: 'F01' })).toBeVisible();
  await expect(review.getByRole('button', { name: 'Inspect note F02' })).toHaveCount(0);
  expect(errors).toEqual([]);
});

test('review iframe cannot execute restored scripts, navigate, submit forms or contact external hosts', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 1000 });
  const fixture = await openResponsiveFixture(page);
  await page.getByRole('button', { name: "Review request: Improve responsive layouts across laptop screens" }).click();
  const requests = [];
  page.on('request', r => { if (r.url().includes('blocked.example')) requests.push(r.url()); });
  const hostile = `<meta http-equiv="refresh" content="0;url=https://blocked.example/refresh"><script>parent.document.body.dataset.artifactExecuted='yes';fetch('https://blocked.example/fetch')</script><img src="https://blocked.example/image" onerror="parent.document.body.dataset.artifactExecuted='yes'"><a href="https://blocked.example/link">Navigate</a><form action="https://blocked.example/form"><button>Submit</button></form><p>Safe target</p>`;
  fixture.send({ type: 'render_update', sessionKey: 'layout-0', leaderSessionKey: 'layout-0', action: 'set', components: [{ id: 'hostile', type: 'html-artifact', html: hostile }] });
  await page.getByRole('tab', { name: 'Dashboard', exact: true }).click();
  // Only test requests from the review document; the regular preview relies on server sanitization.
  requests.length = 0;
  await page.getByRole('button', { name: 'Review & annotate' }).click();
  const frame = page.frameLocator('iframe[title="HTML review viewport"]');
  await frame.getByText('Safe target').click();
  await frame.getByText('Navigate').click();
  await expect(frame.locator('script,form,meta[http-equiv="refresh"]')).toHaveCount(0);
  await expect(frame.getByText('Safe target')).toBeVisible();
  expect(await page.evaluate(() => document.body.dataset.artifactExecuted)).toBeUndefined();
  expect(requests).toEqual([]);
});


test('mobile-first keyboard selection auto-saves notes on close and keeps review usable', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 1000 });
  const fixture = await openResponsiveFixture(page);
  await page.getByRole('button', { name: "Review request: Improve responsive layouts across laptop screens" }).click();
  fixture.send({ type: 'render_update', sessionKey: 'layout-0', leaderSessionKey: 'layout-0', action: 'set', components: [{ id: 'mobile-review', type: 'html-artifact', title: 'Mobile review', html }] });
  await page.getByRole('tab', { name: 'Dashboard', exact: true }).click();
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByRole('button', { name: 'Context Needs attention' }).click();
  await page.getByRole('button', { name: 'Review & annotate' }).click();
  const review = page.getByRole('region', { name: 'HTML feedback workspace' });
  await expect(review.getByRole('combobox', { name: 'Viewport', exact: true })).toHaveValue('360');
  await expect(review.getByLabel('What should change?')).toHaveCount(0);
  await review.getByText('Choose target', { exact: true }).click();
  await review.getByLabel('Keyboard target picker').selectOption({ label: 'p · Subscribe' });
  await expect(review.getByLabel('What should change?')).toBeFocused();
  await review.getByLabel('What should change?').pressSequentially('Make room for the label.');
  await expect(review.getByRole('button', { name: /^(Add note|Save changes)$/ })).toHaveCount(0);
  await page.getByRole('button', { name: 'Close Mobile review feedback' }).click();
  await expect(page.getByRole('alertdialog')).toHaveCount(0);
  await expect(review).toHaveCount(0);
  await page.getByRole('button', { name: 'Review & annotate' }).click();
  await review.getByRole('button', { name: 'Inspect note F01' }).click();
  await expect(review.getByLabel('What should change?')).toBeFocused();
  await expect(review.getByLabel('What should change?')).toHaveValue('Make room for the label.');
  await page.setViewportSize({ width: 390, height: 600 });
  const next = review.getByRole('button', { name: 'New note' });
  await expect(review.getByRole('textbox')).toHaveCount(1);
  for (const selector of ['.hf-sidebar', '.hf-sidebar-body', '.hf-batch-footer']) {
    expect(await review.locator(selector).evaluate(el => el.scrollHeight <= el.clientHeight + 1)).toBe(true);
  }
  await next.scrollIntoViewIfNeeded();
  const buttonBounds = await next.boundingBox();
  expect(buttonBounds.y + buttonBounds.height).toBeLessThanOrEqual(600);
  await next.click();
  await review.getByRole('button', { name: 'Review 1 note' }).click();
  const submit = review.getByRole('button', { name: 'Submit batch (1 note)' });
  await expect(submit).toBeEnabled();
  await submit.hover();
  const colors = await submit.evaluate(el => ({ background: getComputedStyle(el).backgroundColor, accent: getComputedStyle(el).getPropertyValue('--accent').trim() }));
  expect(colors.background).not.toBe('rgba(0, 0, 0, 0)');
});

test('inline replacement is reversible plaintext and can be saved without a separate note', async ({ page }, info) => {
  await page.setViewportSize({ width: 1440, height: 900 });
  const fixture = await openResponsiveFixture(page);
  await page.getByRole('button', { name: "Review request: Improve responsive layouts across laptop screens" }).click();
  fixture.send({ type: 'render_update', sessionKey: 'layout-0', leaderSessionKey: 'layout-0', action: 'set', components: [{ id: 'inline-review', type: 'html-artifact', title: 'Inline review', html }] });
  await page.getByRole('tab', { name: 'Dashboard', exact: true }).click();
  await page.getByRole('button', { name: 'Review & annotate' }).click();
  await page.setViewportSize({ width: 1366, height: 768 });
  const review = page.getByRole('region', { name: 'HTML feedback workspace' });
  const frame = page.frameLocator('iframe[title="HTML review viewport"]');
  await frame.getByText('Subscribe', { exact: true }).click();
  const labelBounds = await review.getByRole('group', { name: 'Selection actions' }).boundingBox();
  const targetBounds = await frame.getByText('Subscribe', { exact: true }).boundingBox();
  expect(labelBounds.y + labelBounds.height).toBeLessThan(targetBounds.y);
  await review.getByRole('button', { name: 'Edit selected text' }).click();
  const inline = frame.getByRole('textbox', { name: 'Edit selected text' });
  await expect(inline).toBeFocused();
  await inline.fill('Join the newsletter');
  await inline.press('Enter');
  await inline.pressSequentially('A new line');
  await review.getByLabel('What should change?').click();
  await expect(review).toBeVisible();
  await expect(inline).toHaveCount(0);
  await expect(review.getByLabel('What should change?')).toBeFocused();
  await expect(review.getByRole('textbox')).toHaveCount(1);
  for (const selector of ['.hf-sidebar', '.hf-sidebar-body', '.hf-batch-footer']) {
    expect(await review.locator(selector).evaluate(el => el.scrollHeight <= el.clientHeight + 1)).toBe(true);
  }
  const textbox = await review.getByLabel('What should change?').boundingBox();
  const controls = await review.locator('.hf-inline-actions').boundingBox();
  expect(textbox.y + textbox.height).toBeLessThanOrEqual(controls.y);
  await page.screenshot({ path: info.outputPath('inline-text-preview.png') });
  await expect(frame.getByText('Join the newsletter A new line', { exact: true })).toBeVisible();
  await review.getByRole('button', { name: 'Review 1 note' }).click();
  await expect(review.getByLabel('Saved feedback')).toHaveValue(/Join the newsletter\nA new line/);
  await review.getByRole('button', { name: 'Inspect note F01' }).click();
  await review.getByRole('button', { name: 'Edit selected text' }).click();
  await expect(frame.getByRole('textbox', { name: 'Edit selected text' })).toHaveText('Join the newsletter\nA new line');
  await review.getByRole('button', { name: 'Undo preview' }).click();
  await expect(frame.getByText('Subscribe', { exact: true })).toBeVisible();
});

test('selection edit label remains outside top-edge content on desktop and mobile', async ({ page }, info) => {
  await page.setViewportSize({ width: 1440, height: 900 });
  const fixture = await openResponsiveFixture(page);
  await page.getByRole('button', { name: 'Review request: Improve responsive layouts across laptop screens' }).click();
  fixture.send({ type: 'render_update', sessionKey: 'layout-0', leaderSessionKey: 'layout-0', action: 'set', components: [{ id: 'edge-label', type: 'html-artifact', html: '<style>body{margin:0;font:18px system-ui}p{margin:0;padding:12px;background:#eee}</style><p>Top edge text</p>' }] });
  await page.getByRole('tab', { name: 'Dashboard', exact: true }).click();
  await page.getByRole('button', { name: 'Review & annotate' }).click();
  const review = page.getByRole('region', { name: 'HTML feedback workspace' });
  const frame = page.frameLocator('iframe[title="HTML review viewport"]');
  for (const width of [1366, 390]) {
    await page.setViewportSize({ width, height: 900 });
    await review.getByRole('combobox', { name: 'Viewport', exact: true }).selectOption(width === 390 ? '360' : '768');
    await frame.getByText('Top edge text', { exact: true }).click();
    const label = review.getByRole('group', { name: 'Selection actions' });
    await expect(label).toBeVisible();
    await expect(label).toContainText('Selected text');
    const bounds = await label.boundingBox();
    const target = await frame.getByText('Top edge text', { exact: true }).boundingBox();
    expect(bounds.y + bounds.height).toBeLessThan(target.y);
    const scrollArea = await review.locator('.hf-canvas-scroll').boundingBox();
    expect(bounds.y).toBeGreaterThanOrEqual(scrollArea.y);
    await page.screenshot({ path: info.outputPath(`selection-label-${width}.png`) });
  }
  await review.getByRole('button', { name: 'Edit selected text' }).click();
  await expect(frame.getByRole('textbox', { name: 'Edit selected text' })).toBeFocused();
  await review.getByRole('button', { name: 'Cancel text edit' }).click();
  await expect(frame.getByRole('textbox', { name: 'Edit selected text' })).toHaveCount(0);
});

test('click-away saves edits locally, Cancel restores the last preview, and other selections keep edits visible', async ({ page }, info) => {
  await page.setViewportSize({ width: 1440, height: 1000 });
  const fixture = await openResponsiveFixture(page);
  await page.getByRole('button', { name: 'Review request: Improve responsive layouts across laptop screens' }).click();
  fixture.send({ type: 'render_update', sessionKey: 'layout-0', leaderSessionKey: 'layout-0', action: 'set', components: [{ id: 'persistent-text', type: 'html-artifact', html }] });
  await page.getByRole('tab', { name: 'Dashboard', exact: true }).click();
  await page.getByRole('button', { name: 'Review & annotate' }).click();
  const review = page.getByRole('region', { name: 'HTML feedback workspace' });
  const frame = page.frameLocator('iframe[title="HTML review viewport"]');
  await frame.getByText('Subscribe', { exact: true }).click();
  await review.getByRole('button', { name: 'Edit selected text' }).click();
  await frame.getByRole('textbox', { name: 'Edit selected text' }).fill('Join us');
  await frame.getByRole('heading', { name: 'Newsletter' }).click();
  await expect(frame.getByText('Join us', { exact: true })).toBeVisible();
  await expect(review.getByRole('button', { name: 'Review 1 note' })).toBeEnabled();
  await review.getByRole('button', { name: 'Edit selected text' }).click();
  await frame.getByRole('textbox', { name: 'Edit selected text' }).fill('Updates');
  await review.getByLabel('What should change?').click();
  await expect(review.getByRole('button', { name: 'Review 2 notes' })).toBeEnabled();
  await frame.getByText('Join us', { exact: true }).click();
  await review.getByRole('button', { name: 'Edit selected text' }).click();
  await frame.getByRole('textbox', { name: 'Edit selected text' }).fill('Unwanted change');
  await review.getByRole('button', { name: 'Cancel text edit' }).click();
  await expect(frame.getByText('Join us', { exact: true })).toBeVisible();
  await expect(frame.getByRole('heading', { name: 'Updates' })).toBeVisible();
  await expect(review.getByRole('button', { name: 'Review 2 notes' })).toBeEnabled();
  await page.screenshot({ path: info.outputPath('persistent-text-previews.png') });
  await page.getByRole('button', { name: 'Close HTML artifact feedback' }).click();
  await page.getByRole('button', { name: 'Review & annotate' }).click();
  await expect(frame.getByText('Join us', { exact: true })).toBeVisible();
  await expect(frame.getByRole('heading', { name: 'Updates' })).toBeVisible();
  await frame.getByText('Join us', { exact: true }).click();
  await review.getByRole('button', { name: 'Discard changes' }).click();
  await expect(frame.getByText('Subscribe', { exact: true })).toBeVisible();
  await expect(frame.getByRole('heading', { name: 'Updates' })).toBeVisible();
  await expect(review.getByRole('button', { name: 'Review 1 note' })).toBeEnabled();
});

test('drawn regions switch to Select, survive without a note, and can be selected after scrolling', async ({ page }, info) => {
  await page.setViewportSize({ width: 1440, height: 1000 });
  const fixture = await openResponsiveFixture(page);
  await page.getByRole('button', { name: 'Review request: Improve responsive layouts across laptop screens' }).click();
  fixture.send({ type: 'render_update', sessionKey: 'layout-0', leaderSessionKey: 'layout-0', action: 'set', components: [{ id: 'regions', type: 'html-artifact', html: html + '<div style="height:1200px"></div>' }] });
  await page.getByRole('tab', { name: 'Dashboard', exact: true }).click();
  await page.getByRole('button', { name: 'Review & annotate' }).click();
  const review = page.getByRole('region', { name: 'HTML feedback workspace' });
  const frame = page.frameLocator('iframe[title="HTML review viewport"]');
  const viewport = page.locator('iframe[title="HTML review viewport"]');
  await review.getByRole('button', { name: 'Draw region' }).click();
  let rect = await viewport.boundingBox();
  await page.mouse.move(rect.x + 100, rect.y + 300);
  await page.mouse.down(); await page.mouse.move(rect.x + 300, rect.y + 380, { steps: 4 }); await page.mouse.up();
  await expect(review.getByRole('button', { name: 'Select', exact: true })).toHaveAttribute('aria-pressed', 'true');
  await expect(review.getByRole('group', { name: 'Selection actions' })).toContainText('Selected region');
  await review.getByRole('button', { name: 'Review 1 note' }).click();
  await expect(review.getByRole('button', { name: 'Submit batch (0 notes)' })).toBeDisabled();
  await expect(review.getByText('Region · add a note')).toBeVisible();
  await review.getByRole('button', { name: 'Continue annotating' }).click();
  await frame.getByRole('heading', { name: 'Newsletter' }).click();
  await expect(review.getByRole('group', { name: 'Selection actions' })).toContainText('Selected text');
  await frame.locator('body').evaluate(el => el.ownerDocument.defaultView.scrollTo(0, 80));
  await review.locator('.hf-canvas-scroll').evaluate(el => { el.scrollTop = 0; });
  await expect(review.locator('.hf-annotation')).toHaveCSS('top', '220px');
  rect = await viewport.boundingBox();
  await page.mouse.move(rect.x + 200, rect.y + 260);
  await expect(review.locator('.hf-hover-outline')).toHaveCSS('height', '80px');
  await page.mouse.click(rect.x + 200, rect.y + 260);
  await expect(review.getByRole('group', { name: 'Selection actions' })).toContainText('Selected region');
  await expect(review.getByRole('heading', { name: 'Note F01' })).toBeVisible();
  await review.getByLabel('What should change?').fill('Reduce this gap.');
  await expect(review.locator('.hf-annotation')).toHaveCount(1);
  await page.screenshot({ path: info.outputPath('region-reselected.png') });
  await review.getByRole('button', { name: 'Review 1 note' }).click();
  await expect(review.getByRole('button', { name: 'Submit batch (1 note)' })).toBeEnabled();
});
