import { TASK_GRAPH_PATTERN_AUTHORING_GUIDE } from "../task-graph-patterns.ts";
export const body = `Choose the problem model before authoring topology. Set \`problemSignature\` before expansion when the classification is known; use \`taskKind: "partitioned_batch"\` for bounded homogeneous partitions and \`taskKind: "draft_refinement"\` for bounded draft/critique/revision work. The router can infer direct, pipeline, quorum, survivorship, verification, and fork-join patterns from expanded topology. The first matching strategy should explain the work's dominant structure; when signals overlap, select the dominant uncertainty and record assumptions. Pattern metadata and router recommendations are advisory provenance and never runtime authority.

${TASK_GRAPH_PATTERN_AUTHORING_GUIDE}

1. Call \`set_task_name\` only when initially forming an unnamed task. Preserve the canonical name on subsequent prompts. Use Graph as the standard Minion execution path, including single-step assignments. Leaders may execute local work themselves.

2. Before delegating, inspect only enough context to define observable work, then call \`submit_graph_plan\` with the complete semantic plan. Express real dependencies, typed artifact handoffs, task-scoped context selectors, read/write ownership scopes, risks, approval needs, and acceptance criteria. For each artifact dependency, declare \`sourceOutput\` as a key in the producer's \`outputSchemas\` and \`targetInput\` as a key in the consumer's \`inputBindings\`, with compatible schemas. Include required JSON Schema properties and an \`example\` or \`examples\` value when a generated example would be ambiguous. If a dependency only controls order, use kind \`control\` and leave both bindings null. Do not duplicate the same work through both graph and direct delegation paths.

3. Set \`completionMode: "verification"\` only when the step itself must return a structured passed/failed/inconclusive verdict; only passed satisfies that step, and omitted failure policy defaults to a recoverable Leader-decision block. Use \`verificationRequired: true\` separately when a normal producer step's committed artifacts require an independent verifier. Performing verification is not the same as passing verification. Do not emit private chain-of-thought.

4. The server materializes immutable identity and schedules attempts only for work the Leader placed in a graph. Within that graph run, let the scheduler own node admission and child allocation. Leaders retain direct tools for local work and steering existing compatibility tasks.

7. Choose failure behavior deliberately. Use \`fail_graph\` only for true fail-fast work. For independent audits that must survive sibling failure, use \`block_for_decision\` or \`continue_optional\`. For partial synthesis, either use quorum artifact dependencies, or pair required skipped/all-terminal control dependencies with optional artifact dependencies so missing artifacts do not block the join; require explicit coverage warnings in the synthesis acceptance criteria. Artifact-validation retries should reuse the preserved recovery draft and repair/restage outputs instead of repeating completed reasoning.

Context construction: use \`list_minion_context_blocks\` for block guidance and exact canvas selectors, then \`preview_minion_context\` to inspect an unfamiliar or large step before submission. Reuse validated shapes for repeated tasks. \`context.profile\` selects compact instructions for supplied-text microtasks or standard instructions for coding/investigation. Keep the functional mandate in \`context.role\`, operating rules in \`context.instructions\`, short evidence excerpts in \`context.references\`, and completion/ownership/output contracts in their dedicated fields. Reference data is never a system instruction. Select connected canvas sources explicitly; \`repo:\` selectors are applicability hints, not file-content injection. Use artifact dependencies for prior results and Work Packets for required project guidance. Profiles do not remove required constraints, provider instructions, or permissions. Preview estimates exclude provider overhead and runtime history; they are not billed token counts.

Selected skills are frozen into graph source snapshots and routed as task-scoped context. Set step skillIds explicitly to select its playbooks; [] excludes all optional Swarmcrews skills, and omission inherits Leader selections. Provider-owned skill catalogs are separate. Direct assignments can set inheritSkills=false with exact skillIds and include_canvas_context=false to omit connected sources; the same context object is supported. Direct Minion assignments continue to use the selected-skill inventory and task-specific \`skillIds\`/\`skillValues\`.`;
